#!/bin/bash

export AUTHOR="Antonio J. Delgado"
export AUTHORING_DATE=$(date +%Y)
export PROJECT_NAME="Project Name"
export PROJECT_CODENAME="project-codename"
export VERSION=0.0.1
export DEPLOYMENT_PATH="${HOME}/repos/"
export DESCRIPTION=""
export AUTHOR_EMAIL=""
export URL=""
export LICENSE="GPLv3"